linear:
	g++ mandelbrot_linear.cpp -o mandelbrot_linear

threaded:
	g++ mandelbrot_paralelizado.cpp -o mandelbrot_paralelizado -fopenmp

clean:
	rm -f mandelbrot_linear mandelbrot_paralelizado *.ppm

